### ISSUE TITLE
Broken Static Binaries

### ISSUE THREAD

**Issue by Azathothas** [root4loot/rescope#14]
The static binaries released here, all contain hardcoded path for `configs/avoid.txt`
![image](https://github.com/root4loot/rescope/assets/58171889/ecfeed07-eff7-4e06-89a3-eefcefe57a43)

Building it locally on my `/tmp/` dir, indeed, the path is hardcoded!
![image](https://github.com/root4loot/rescope/assets/58171889/8ea4e009-3d26-4fb4-b8e3-ef136db9c723)

**Comment by root4loot** [comment]
@Azathothas Thank you for reporting this.

The path is not hardcoded intentionally; it appears to have been a side effect of a bug in [goreleaser](https://github.com/goreleaser/goreleaser) during the time of the previous release. I've since compiled new binaries that should resolve the issue. If you previously downloaded the binary from the v2.4 release, I would recommend deleting the old binary first before downloading and installing the updated one from the same release tag. I've replaced the binaries under that tag with the fixed version.

```
go install github.com/root4loot/rescope@latest
```

![image](https://github.com/root4loot/rescope/assets/44880186/71817e97-dbd9-4cf5-a5a4-1dd94722c4e3)
